#
# Module manifest for module 'PsConsumerPipeline'
#
# Generated by: Jonathan W. MacCollum
#
# Generated on: 8/27/2024
#

@{
    RootModule="PsConsumerPipeline.psm1"
    ModuleVersion = '1.0.1'
    GUID = 'd1f34a3e-e8fe-4549-9293-90464b626e8d'
    Author = 'Jonathan W. MacCollum'
    Copyright = '(c) Jonathan W. MacCollum. All rights reserved.'

    Description = 'Parallel processing of pipeline input using multiple consumers'

    PowerShellVersion = '7.0'

    ScriptsToProcess = @(
    )

    NestedModules = @(
    )

    FunctionsToExport = @(
        'Invoke-ConsumerPipeline'
    )

    CmdletsToExport = @(
    )

    VariablesToExport = ''

    AliasesToExport = @()

    PrivateData = @{

        PSData = @{


        }

    }

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}

